name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  unzip_and_deploy:
    runs-on: ubuntu-latest
    environment: unzip  # Use the unzip environment

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Unzip the project archive
      run: unzip -o rag_llm_project_enhanced.zip -d .
