name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download executable
      uses: actions/download-artifact@v3
      with:
        name: your-executable
        path: ./executable

    - name: Remove existing service (if any)
      run: |
        sudo systemctl stop your-service-name || true
        sudo systemctl disable your-service-name || true
        sudo rm /etc/systemd/system/your-service-name.service || true
      continue-on-error: true

    - name: Copy executable to /usr/local/bin
      run: |
        sudo cp ./executable/your_executable_name /usr/local/bin/your_executable_name
        sudo chmod +x /usr/local/bin/your_executable_name

    - name: Create systemd service file
      run: |
        echo "[Unit]
        Description=Your Flask Application Service
        After=network.target

        [Service]
        ExecStart=/usr/local/bin/your_executable_name
        WorkingDirectory=/usr/local/bin
        Restart=always
        User=your_user
        Group=your_group
        Environment=PORT=5000

        [Install]
        WantedBy=multi-user.target" | sudo tee /etc/systemd/system/your-service-name.service

    - name: Start and enable the service
      run: |
        sudo systemctl daemon-reload
        sudo systemctl start your-service-name
        sudo systemctl enable your-service-name

    - name: Verify deployment
      run: |
        sleep 10  # Wait a bit for the service to start
        curl --fail http://localhost:5000 || (echo "Deployment failed"; exit 1)