name: Deploy MortyRAG Docker Image

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ghcr.io/agreene90/mortyrag:latest \
            --label "org.opencontainers.image.title=MortyRAG" \
            --label "org.opencontainers.image.description=A Retrieval-Augmented Generation (RAG) model designed to generate witty, informative, and contextually accurate responses, with a focus on physics." \
            --label "org.opencontainers.image.authors=agreene90" \
            --label "org.opencontainers.image.source=https://github.com/agreene90/MortyRAG" \
            --label "org.opencontainers.image.version=latest" .
          
          docker push ghcr.io/agreene90/mortyrag:latest
