name: Deploy MortyRAG Docker Image

on:
  workflow_run:
    workflows: ["Build and Test MortyRAG Docker Image"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ghcr.io/agreene90/mortyrag:latest .
          docker push ghcr.io/agreene90/mortyrag:latest

      - name: Prune Docker System to Free Up Space
        run: |
          docker system prune -af --volumes
