name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  unzip_and_deploy:
    runs-on: ubuntu-latest
    environment: unzip  # Specify the environment here

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Unzip the project archive
      run: unzip -o rag_llm_project_enhanced.zip -d temp_unzip

    - name: Move files to the root directory
      run: |
        mv temp_unzip/* .
        mv temp_unzip/.* . || true
        rm -rf temp_unzip

    - name: Commit changes
      env:
        GIT_SSH_COMMAND: "ssh -i ${{ secrets.ACTIONS_DEPLOY_KEY }} -o StrictHostKeyChecking=no"
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add .
        git commit -m "Unzip and deploy project files"
        git push origin main
