name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Cache pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Prepare directories and check for existing knowledge base
      run: |
        mkdir -p data/processed
        if [ ! -f "data/processed/vectorizer.pkl" ]; then
          echo "Knowledge base binaries not found. Running setup script..."
          python src/data_ingestion.py  # Run your data ingestion or setup script here
        else
          echo "Knowledge base binaries found. Skipping setup."
        fi

    - name: Run unit tests
      run: python -m unittest discover -s tests

    - name: Build Docker image
      run: docker build -t your-rag-system .

    - name: Save Docker image to cache
      uses: actions/cache@v3
      with:
        path: /home/runner/work/_temp/docker_cache
        key: docker-${{ runner.os }}-${{ hashFiles('Dockerfile') }}
        restore-keys: |
          docker-${{ runner.os }}

    - name: Test Docker image
      run: docker run --rm your-rag-system python -m unittest discover -s tests

    - name: Publish Docker image
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: |
        echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
        docker tag your-rag-system:latest your-dockerhub-username/your-rag-system:latest
        docker push your-dockerhub-username/your-rag-system:latest
