name: Build and Run Docker Container

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: |
        docker build --progress=plain --compress -t ghcr.io/${{ github.repository_owner }}/mortyrag:latest .

    - name: Run Docker container
      run: |
        docker run -d --name mortyrag-container -p 5000:5000 ghcr.io/${{ github.repository_owner }}/mortyrag:latest

    - name: Save Docker image to tar file
      run: |
        docker save --compress ghcr.io/${{ github.repository_owner }}/mortyrag:latest -o mortyrag.tar

    - name: Upload Docker image as artifact
      uses: actions/upload-artifact@v3
      with:
        name: mortyrag-image
        path: mortyrag.tar

    - name: Clean up Docker resources
      run: |
        docker container stop mortyrag-container
        docker container rm mortyrag-container
        docker rmi ghcr.io/${{ github.repository_owner }}/mortyrag:latest