name: Build and Push Docker Image

on:
  push:
    tags:
      - '*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Tag Docker Image
      run: |
        TAG_NAME=${{ github.ref_name }}
        docker build -t ghcr.io/agreene90/mortyrag:latest -t ghcr.io/agreene90/mortyrag:${TAG_NAME} .

    - name: Push Docker Image to GitHub Container Registry
      run: |
        TAG_NAME=${{ github.ref_name }}
        docker push ghcr.io/agreene90/mortyrag:latest
        docker push ghcr.io/agreene90/mortyrag:${TAG_NAME}