name: Build MortyRAG Executable

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build executable with PyInstaller
      run: |
        pyinstaller --onefile --noconsole --name MortyRAG main.py

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: mortyrag-executable
        path: dist/MortyRAG
        retention-days: 5  # Optionally specify how long to keep the artifacts