name: Build and Release MortyRAG Executable

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build executable with PyInstaller
      run: |
        pyinstaller --onefile --noconsole --name MortyRAG main.py

    - name: Archive executable
      uses: actions/upload-artifact@v3
      with:
        name: mortyrag-executable
        path: dist/MortyRAG

  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create a Git Tag
      run: |
        git config --local user.name "GitHub Actions"
        git config --local user.email "actions@github.com"
        git tag v$(date +'%Y.%m.%d.%H%M%S')
        git push origin --tags

    - name: Deploy to Releases
      uses: softprops/action-gh-release@v1
      with:
        files: dist/MortyRAG
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: dist/MortyRAG
        retention-days: 5  # Optionally specify how long to keep the artifacts

  # test:
  #   runs-on: ubuntu-latest
  #   needs: build

  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v3

  #   - name: Set up Python environment
  #     uses: actions/setup-python@v4
  #     with:
  #       python-version: '3.10'

  #   - name: Install dependencies
  #     run: |
  #       python -m pip install --upgrade pip
  #       pip install -r requirements.txt

  #   - name: Run tests
  #     run: |
  #       python -m unittest discover -s tests