name: Build and Run Docker Container

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: |
        docker build -t mortyrag .

    - name: Run Docker container
      run: |
        docker run -d -p 5000:5000 mortyrag

    - name: Save Docker image as artifact
      uses: actions/upload-artifact@v3
      with:
        name: mortyrag-image
        path: |
          ./mortyrag.tar

    - name: Save Docker image to tar file
      run: |
        docker save mortyrag -o mortyrag.tar