name: Build MortyRAG Docker Image and Save as Artifact

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker image
      run: |
        docker build -t ghcr.io/agreene90/mortyrag:latest .

    - name: Push Docker image to GitHub Container Registry
      run: |
        docker push ghcr.io/agreene90/mortyrag:latest

    - name: Save Docker image as artifact
      run: |
        docker save ghcr.io/agreene90/mortyrag:latest -o mortyrag.tar

    - name: Upload Docker image artifact
      uses: actions/upload-artifact@v3
      with:
        name: mortyrag-docker-image
        path: mortyrag.tar
        retention-days: 5  # Optionally specify how long to keep the artifacts